# Generated by Django 5.0.2 on 2024-03-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEgreso', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.FloatField()),
                ('titularNombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FormasDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('credito', models.BooleanField()),
                ('descripcion', models.CharField(max_length=200)),
                ('montosAcumulados', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIngreso', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.FloatField()),
                ('formaDePago', models.CharField(max_length=40)),
                ('titularNombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
