# Generated by Django 5.0.2 on 2024-03-12 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanzasApp', '0002_formadepago_delete_formasdepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='formaDePago',
        ),
        migrations.AddField(
            model_name='egreso',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Format: YYYY-MM-DD'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='formaDePago',
            field=models.CharField(default='Efectivo', max_length=40),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Format: YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
    ]
